# To find available Node images, see https://mcr.microsoft.com/en-us/product/devcontainers/javascript-node/tags

# [Choice] Node.js version
ARG VARIANT="dev-24-bullseye"
FROM mcr.microsoft.com/devcontainers/javascript-node:${VARIANT}
https://microsoft.js.node.javascript.domain-node:$$$been come to include on the SERIEL No.

